version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=Nussknacker
      - POSTGRES_PASSWORD=Nussknacker
      - POSTGRES_DB=Nussknacker
    ports:
      - '5432:5432'

volumes:
  db:
    driver: local